### ISSUE TITLE
Summary records not in agreement with raw

### ISSUE THREAD

**Issue by retzkek** [opensciencegrid/gracc-request#21]
In a comparison of raw vs summary records it appears that the summarization process is losing data. https://gracc.opensciencegrid.org/dashboard/db/raw-vs-summary

Some quick ideas:
- limited number of buckets being returned
- records missing fields
- incomplete aggregation due to failing shards

**Comment by djw8605** [comment]
First attempt of disabling bucket limiting in #20

**Comment by djw8605** [comment]
Ok, I think we have this fixed!
