### ISSUE TITLE
Summaries lag a day behind

### ISSUE THREAD

**Issue by retzkek** [opensciencegrid/gracc-request#23]
Since the from and to dates are truncated, summaries for "today" don't appear until "tomorrow". We should either leave the times intact (and expect the client to understand the ramifications of requesting a partial day), or round the to date up.

``` python
        # For summaries, we only summarize full days, so strip the time from the from & to
        from_date = dateutil.parser.parse(from_date).date()
        to_date = dateutil.parser.parse(to_date).date()
```

https://github.com/opensciencegrid/gracc-request/blob/master/src/graccreq/summary_replayer.py#L59-L61

**Comment by djw8605** [comment]
Fixed in #28
